import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "platein",
  description: "Generated by bees",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
      </body>
    </html>
  );
}
