import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import Footer from "../components/Footer";
import SidebarContainer from "@/components/sidebar/SidebarContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "platein",
  description: "Generated by bees",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-indigo-50 flex flex-col min-h-screen`}>
        <div className="flex-grow">
          <SidebarContainer/>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
